FROM jboss/keycloak:latest

ENV KEYCLOAK_BLOCKCHAIN_INTEGRATION_FILE_NAME keycloak-events.jar
ENV KEYCLOAK_BLOCKCHAIN_INTEGRATION_VERSION 0.0.1
ENV KEYCLOAK_DIRECTORY /opt/jboss/keycloak
ENV KEYCLOAK_BIN_DIRECTORY ${KEYCLOAK_DIRECTORY}/bin
ENV KEYCLOAK_CLI_FILE jboss-cli-configuration.txt
ENV KEYCLOAK_POST_CONFIGURE_FILE keycloak-postconf.sh
ENV WORKING_DIR /root/keycloak

USER root
RUN mkdir ${WORKING_DIR}
WORKDIR ${WORKING_DIR}

ADD ${KEYCLOAK_CLI_FILE} ${WORKING_DIR}

ADD ${KEYCLOAK_POST_CONFIGURE_FILE} ${WORKING_DIR}
RUN chmod +x ${WORKING_DIR}/${KEYCLOAK_POST_CONFIGURE_FILE}

RUN curl -L https://github.com/arigatooo/keycloak-blockchain-integration/releases/download/${KEYCLOAK_BLOCKCHAIN_INTEGRATION_VERSION}/${KEYCLOAK_BLOCKCHAIN_INTEGRATION_FILE_NAME} > ${WORKING_DIR}/${KEYCLOAK_BLOCKCHAIN_INTEGRATION_FILE_NAME}

RUN ${KEYCLOAK_BIN_DIRECTORY}/jboss-cli.sh --file=${WORKING_DIR}/${KEYCLOAK_CLI_FILE}
RUN ${KEYCLOAK_BIN_DIRECTORY}/add-user-keycloak.sh -u test -p test

RUN rm ${WORKING_DIR}/${KEYCLOAK_CLI_FILE}
RUN rm ${WORKING_DIR}/${KEYCLOAK_BLOCKCHAIN_INTEGRATION_FILE_NAME}

RUN rm -rf ${KEYCLOAK_DIRECTORY}/standalone/configuration/standalone_xml_history/current/*

ENTRYPOINT [ "/opt/jboss/docker-entrypoint.sh" ]
CMD ["-b", "0.0.0.0"]